### ISSUE TITLE
can not play x265 10bit on my device

### ISSUE THREAD

**Issue by lemony8734** [mpv-android/mpv-android#105]
CPU: arm cortex-a17
GPU: Mali-T760

can not use the hardware decoding for x265 10bit video.
![image](https://user-images.githubusercontent.com/9963825/37022447-056d810c-215e-11e8-8a4d-f2f82a4cc32b.png)

kodi is working fine.

use mpv-android play the same file on my cellphone, is working fine.
this makes me very confused.

**Comment by sfan5** [comment]
In my experience trying to use mediacodec for 10-bit will either 1) fallback to some software implementation or 2) produce broken output
maybe @tmm1 knows something about this

**Comment by lopoki** [comment]
I had the same problem on Nvidia shield but solved it by disabling HW decoder manually. Shield cpu and gpu is powerful enough for high bit rate x265 10 bit

**Comment by sfan5** [comment]
I've made some adjustments to prevent using software implementations while hwdec is reported as enabled.
Please try if you can: https://kitsunemimi.pw/tmp/mpv-android-2018-03-07.apk

**Comment by lopoki** [comment]
Hi sfan, software codec is very useful to play x265 10 bit, divx abd many other older codec that's not perfectly supported by hwdec (media codec).

I believe what we need is first mpv to try to decode A, V using hwdec, if fail, then try using software codec for A and V. Most likelt the outcome would be using hwdec (media codec) for Audio, and using software codec(cpu)  for video for odd codec and x265 10bit. This is the same flow as in mx player.

In any case, i believe mpv should preserve the ability to use different kind of upscaling and downscaling algorithm such as lanczos etc because this is what makes mpv so much better than rest (kodi, plex, mx player, vlc, yes player, exoplayer) etc.
I believe all others use plain media codec which default to the bilinear algorithm.
I tested both in cheap Chinese tv box rk3688-device and nvidia shield tv using latest mpv, it's great results for using lanczos for upscaling 720p to 4k or 1080p

**Comment by sfan5** [comment]
@lemony8734 
Thanks for testing. Which device are you on?

@lopoki 
> software codec is very useful to play x265 10 bit, divx abd many other older codec that's not perfectly supported by hwdec (media codec).

I was talking about the software codecs offered through `MediaCodec`. These are often inferior and slower than ffmpeg's builtin decoders, so they should be avoided.
H.265, DivX and others will always be playable in mpv-android since ffmpeg provides decoders.

> I believe what we need is first mpv to try to decode A, V using hwdec, if fail, then try using software codec 

This is current behaviour (unless you disable hwdec in settings) for video. Audio is always decoded in software.

**Comment by lopoki** [comment]
I agree i tend to find mediacodec is inferior. In powerful devices such as nvidia shield, mpv with ffmpeg is much better quality.

I didn't disable hwdec in settings, in the latest mpv android release mpv played the 10bit x265 video garbled just like reported in above screen shot. Then i would need to bring up OSD and change hwdec into software. Sorry for any misunderstanding

**Comment by lemony8734** [comment]
@sfan5 I tested on my projector. GIMI H1, https://en.xgimi.com/h1/function.html
kodi works perfectly on my projector.

thanks.

**Comment by sfan5** [comment]
Your device does have a proper hardware decoder (`OMX.MS.HEVC.Decoder`), so I guess we need to add a different workaround for 10-bit media.

**Comment by sfan5** [comment]
Likely stale.
