### ISSUE TITLE
Portrait video on portrait screen shows in landscape orientation

### ISSUE THREAD

**Issue by jaimet** [mpv-android/mpv-android#128]
Hi.

I'm trying to view a portrait video on my phone when the screen itself is in portrait orientation. Using lineage's built-in ("stock") video player, the playback orientation is exactly as I want:

![viewusingbuiltinstockvideoplayer](https://user-images.githubusercontent.com/8218065/41471349-4b83c920-70ab-11e8-8128-7d006ee134ec.png)

When I view the same video using mpv-android, the playback image is rotated (to landscape):

![viewusingmpvandroid](https://user-images.githubusercontent.com/8218065/41471350-4ba78950-70ab-11e8-837c-7ac6d48ee456.png)

I've had a dig around but I can't find anything that might change the playback orientation. Let me know if you want me to upload the video somewhere (I've tried attaching it to this issue, but of course github doesn't accept video files as attachments).

Thank you for porting mpv to android, by the way. I use mpv on all my linux boxes, and I am very grateful to you for making mpv available on android.

**Comment by kmkipta** [comment]
There is similar behavior when playing audio files on Android 8.1 _and_ 9.0, where the album art and controls are stuck in landscape layout. Going to take a quick look as time permits.

mpv-android version is 2018-04-29-alpha /14 (debug)

**Comment by toxtox** [comment]
I just installed mpv from f-droid repo. Wow, it is really fast!!!
If someone @jeeb @sfan5 could fix this (old) bug, that portrait videos are played in landscape, mpv would be the smartest opensource video player for android.

**Comment by sfan5** [comment]
This has been fixed since ecd71d883269d2c9d6d9fe34b311d0458282f380, by the way.

**Comment by toxtox** [comment]
@sfan5 
I compiled the master tree and I found the options for _"Screen orientation"_ in the settings.
But I have **another problem**: the **official release** provides the **required libs in** __"/data/apps/is.xyz.mpv-1/lib"_ but these **libs** are **missing** if I **compile _"mpv-android"_ myself**.
Saving the libs of the official release and copying these libs to the empty .../lib directory of my self-compiled mpv-android installation does not help.
**_Logcat_** still shows a **_FATAL EXCEPTION_** because _**"...couldn't find "libmpv.so"**_

**Is there an unofficial apk-file available that already contains these libs?**
If not, how could I create an apk-package including the required libs?

[app-debug_mpv_android_but_missing_libs_20190103_apk_.zip](https://github.com/mpv-android/mpv-android/files/2725241/app-debug_mpv_android_but_missing_libs_20190103_apk_.zip)

**Comment by sfan5** [comment]
You need to follow the special build instructions if you want to compile mpv-android.

> Is there an unofficial apk-file available that already contains these libs?

You can always check the latest travis build: https://travis-ci.org/mpv-android/mpv-android
Scroll to the bottom and find the `http://0x0.st/.....` URL, there's your apk.

**Comment by toxtox** [comment]
@sfan5 
Thanks a lot for the link to the unofficial mpv-apk. 
If I choose "**_Default Landscape_**" or "**_Default Portrait_**" I can rotate manually the video orientation to landscape or portrait by pressing the onscreen rotation-button on right top or right lower edge. 
"**_Automatic_**" seems not to have any effect on my device (no 90° rotation only 180° rotation as before).
**But the manual rotation option is just fine for me :-)**

**Comment by Keith94** [comment]
For my case, automatic mode seems to have a bug where a portrait video still displays in landscape.

**Comment by sfan5** [comment]
If you experience a bug where a landscape (not square!) video is played in portrait (or the other way around) in <i>Automatic</i> mode, please open a bug **with a logcat log**.

**Comment by Keith94** [comment]
How can I get a logcat log?

**Comment by sfan5** [comment]
> [logcat](https://developer.android.com/studio/command-line/logcat) is part of the Android SDK.
Start logcat, then start mpv-android and reproduce the bug and save the output that was printed during that time.
