### ISSUE TITLE
When a video was playing, opening another one do not launch it

### ISSUE THREAD

**Issue by Geobert** [mpv-android/mpv-android#162]
I've open a video from file manager, hit home button, open another video from file manager, mpv stays on the old video, paused instead of opening the new video.

**Comment by Geobert** [comment]
It works if I press back instead of Home

**Comment by kn-yami** [comment]
It works like that, because pressing the back button will close the application but pressing the home button will only hide it. If you try to open a new file while the application is already running Android will bring the application to front.

**Comment by Geobert** [comment]
I understand that (I was an Android dev some years ago), but from a user point of view, it feels weird: he asks for this new file to play, and we're stuck on the previous one. It doesn't sound very intuitive :-/

**Comment by kn-yami** [comment]
Well, this was never a problem for me, because I do not use the home button to "close" applications. Opening a new file while the application is already running may be possible (IIRC you can send the `loadfile` command while playing another file) depending on the method that Android uses to tell the application which file to open (I have never did any Android programming so IDK how it does that).

**Comment by Geobert** [comment]
I can deal with it as well, I was just suggesting that the majority of user would expect that when calling mpv with another file, they get this file to play, whatever state mpv is in.
