### ISSUE TITLE
How is this MIT license if the base mpv is GPL?

### ISSUE THREAD

**Issue by s3433557** [mpv-android/mpv-android#189]
I saw this library was licensed as MIT, however the mpv which this is based on is licensed under one of the GPLs which is more restrictive.

Just wondering how that could be?

**Comment by kn-yami** [comment]
AFAIK the Android front-end code is licensed under MIT and the back-end libmpv is licensed under GPL/LGPL.

**Comment by xyzz** [comment]
mpv/ffmpeg libraries can be compiled with the LGPL configuration option, so that produced binaries are LGPL-licensed. Further, the libmpv API we're using is licensed under ISC. Because of that, we did not want to restrict users of mpv-android code base to GPL and put it under MIT. Now, the builds we redistribute are compiled with GPL options which are the defaults for mpv, and as far as I'm aware we're compliant by providing access to the source code.

**Comment by s3433557** [comment]
So how do other users avoid compilation with the GPL options?

**Comment by xyzz** [comment]
You can compile mpv with the `--enable-lgpl` switch. Our ffmpeg flags should be LGPL-compatible afaik. That said, if you plan to use mpv-android in a product, I highly suggest going through your lawyer before you commit to it.
