### ISSUE TITLE
a/v out of sync

### ISSUE THREAD

**Issue by prspkt** [mpv-android/mpv-android#200]
On the latest `2019-04-18 Test Build` audio seems to consistently run slightly ahead of time compared to the video. The _effect_ is subtle but does not occur on the previous `2018-04-29 Test Build`.

**Comment by sfan5** [comment]
Can confirm. This is incredibly if you watch a release with (properly timed) karaoke.

**Comment by sfan5** [comment]
Reverting mpv-player/mpv@e1bd5288b7050fe34016f4f01c8d3be49a1d7d01 improves A/V sync a lot, though it's still not perfect.

**Comment by sfan5** [comment]
Restoring the second buffer ontop of the current ao_opensles code ([https://gist.github.com/sfan5/c3c8095ab51c51269f57529b45f220ac](patch)) also fixes the issue.

**Comment by tomty89** [comment]
AFAICT when I fixed the buffering code, I didn't really make any changes to the delay calculation. So very likely it became / is still wrong.

I don't exactly know / remember how it works in mpv (e.g. the `2 *` and the correct way/approach to use `mp_time_us` or alike). I tried to make it more sensical (#6147) but it seems the effect varies among devices. (Maybe just because the approach was wrong anyway.)

Also essentially I have only been using mpv in Android for audio-only playback (Termux).

So do what you must. I don't think I can do much more on this. (I do think the buffering code itself is fine though.)

**Comment by tomty89** [comment]
Perhaps we can implement the multiple buffering in a more proper way, if it has to be implemented, as a workaround or anything.

We can have an array of buffers and a buffer index in the private data, and make the number of buffers configurable. (The numBuffers value is also the maximum number of buffers we can do enqueue manually in `resume`.)

**Comment by tomty89** [comment]
The bottom line is, please make "double buffering" an option (and better make it default only in mpv-android).

I just don't like "hardcoding" two bufs as the code looks ugly/clumsy, but I am not sure if array or double pointer should be used in our case.

Also we need to split the soft buffer against the number of buffers as well, otherwise there would be buffer underflow on pause/resume and so. (Somehow even when I do that, more than two buffers causes issue as well. That's why I really don't/didn't want to allow more than one.)

**Comment by tomty89** [comment]
By "consistently" you mean it gets more and more ahead?

Can you try this, if not:
```
diff --git a/audio/out/ao_opensles.c b/audio/out/ao_opensles.c
index 8c24320406..2aec761534 100644
--- a/audio/out/ao_opensles.c
+++ b/audio/out/ao_opensles.c
@@ -39,6 +39,7 @@ struct priv {
     int bytes_per_enqueue;
     pthread_mutex_t buffer_lock;
     double audio_latency;
+    int resumed;

     int frames_per_enqueue;
     int buffer_size_in_ms;
@@ -79,7 +80,7 @@ static void buffer_callback(SLBufferQueueItf buffer_queue, void
 *context)

     pthread_mutex_lock(&p->buffer_lock);

-    delay = 2 * p->frames_per_enqueue / (double)ao->samplerate;
+    delay = (1 + p->resumed)  * p->frames_per_enqueue / (double)ao->samplerate;
     delay += p->audio_latency;
     ao_read_data(ao, &p->buf, p->frames_per_enqueue,
         mp_time_us() + 1000000LL * delay);
@@ -231,12 +232,14 @@ static void reset(struct ao *ao)
 {
     struct priv *p = ao->priv;
     (*p->buffer_queue)->Clear(p->buffer_queue);
+    p->resumed = 0;
 }

 static void resume(struct ao *ao)
 {
     struct priv *p = ao->priv;
     buffer_callback(p->buffer_queue, ao);
+    p->resumed = 1;
 }

 #define OPT_BASE_STRUCT struct priv
```

**Comment by sfan5** [comment]
here's the fix actually mpv-player/mpv#6867

**Comment by prspkt** [comment]
>By "consistently" you mean it gets more and more ahead?

No, I mean it affects all videos that contain audio. The offset seems to be the same and doesn't increase as playback progresses.

**Comment by aufkrawall** [comment]
Could this also be causing issues with mistimed frames when using `--video-sync=display-resample`? Though for whatever reason this is much more distinct for me when using `--hwdec=mediacodec-copy`.

**Comment by sfan5** [comment]
> Could this also be causing issues with mistimed frames when using --video-sync=display-resample? 

Yes, this also entirely fixes interpolation.
