### ISSUE TITLE
Video corruption

### ISSUE THREAD

**Issue by tidux** [mpv-android/mpv-android#23]
I'm not sure if this is a hardware decoder limitation or a bug, but 1080p H.264 has severe blocking problems during high-speed sequences, even on a Pixel C tablet.  Is there an mpv.conf exposed in a user-writable directory to fine tune the output like on the desktop version?

**Comment by jeeb** [comment]
With the settings screen added with the 2016-07-31 build some options are now set'able through the settings UI by @joshdekock (I only generally tested that it should work with the HW decoding entry, so expect boogs, which of course can be fixed if someone reports them). Otherwise - as we set the config path for libmpv - you can copy the mpv.conf file into the `applicationContext.filesDir.path` with adb with something like:
```
<copy the mpv.conf to your sdcard>
adb shell
run-as is.xyz.mpv
cp /path/to/sdcard/mpv.conf files/mpv.conf
```
(use `cat` instead of `cp` if `cp` doesn't work)

**Comment by tidux** [comment]
SW decoder (DivX video in Ogm container) has a bug where switching audio tracks mutes audio.  Even switching back to the first audio track doesn't restore audio.

**Comment by jeeb** [comment]
That setting should already be available, `Settings→General→Hardware decoding`. You might have to force the player component to re-init for the default to take force as I think it isn't being re-loaded @ `onResume`.

Regarding OGM, oh boy. I am reminded of a similar issue with LAV Splitter, so it might be a common issue in libavformat :D (frame rate fuck-ups also happened with LAV, although I haven't seen that with mpv yet - granted I do not play too many OGM files). Not sure how much could be done regarding this, but if it can be replicated with desktop mpv as well it could be reported to FFmpeg. If it's mpv-android specific then it's a separate issue and in both cases a sample would be welcome for testing.

**Comment by tidux** [comment]
Any of the ogm files within https://gateway.ipfs.io/ipfs/QmYRsSadz9L7VBtfgdJYdxyRzcAuaxrHUih5zZY3UzQFo2 will work as a sample.
