### ISSUE TITLE
Feature request: Display HW decoding time

### ISSUE THREAD

**Issue by Consti10** [mpv-android/mpv-android#235]
Hello,
We noticed  that mpv-android works really good with ultra low latency video. Do you have any in-built function to display the parsing & HW decoding time in ms/us resolution ? E.g. the time between a internet video packet arriving and the video frame being decoded ?

**Comment by sfan5** [comment]
Good question, I don't think there is.
There is a [section](https://mpv.io/manual/master/#low-latency-playback) of the manual describing low-latency playback and you might get a better answer at [mpv-player/mpv](https://github.com/mpv-player/mpv) since libmpv handles the details of playback/presentation.
