### ISSUE TITLE
Gestures for zoom in/out, screenshots

### ISSUE THREAD

**Issue by azev** [mpv-android/mpv-android#323]
Feature request:

- zoom in/out (when drag vertically)
- take screenshots (when double click on screen)

**Comment by crisalis2** [comment]
The gesture for zoom-in/out is a very good idea. Most phones today are wider than 16:9, which means most movies (which are also wider than 16:9 but have black bars up and down encoded into the video itself) end up with black bars in all four sides while being displayed in mpv. With the ability to zoom in, you can get rid of all or most of that useless black. A similar problem exists with portrait videos that are encoded as landscape with black in both sides, which also can be solved with the ability to zoom in.

There are two options in mpv for this, video-zoom and panscan. I use panscan in the config, but video-zoom is probably more flexible. Even if the gesture isn't implemented, I think panscan or video-zoom should still be one of the options that appear in mpv-android's quick settings that can be changed without closing the video. It's an arguably more useful setting than many of the options that already appear there.

**Comment by sfan5** [comment]
FYI a panscan gesture already exists (#334)

**Comment by crisalis2** [comment]
Oh, I didn't notice that addition, nice. Just a thought - Maybe it could be improved by adding more steps instead of just 0 and 1, because sometimes panscan=1 is too much.By the way, I remember I disabled tap gestures (when "zoom" still wasn't an option) because they have a negative side effect. When they aren't enabled, you can quickly hide the controls right away by just tapping once anywhere in the screen. But you can't do this if you enable a tap gesture. When a tap gesture is enabled, even if you tap only once trying to just hide the controls, the controls are still displayed for a while.El 3 may. 2021 7:49, sfan5 ***@***.***> escribió:
FYI a panscan gesture already exists (#334)

**Comment by Pentaphon** [comment]
> Maybe it could be improved by adding more steps instead of just 0 and 1, because sometimes panscan=1 is too much.

I think this is a good idea. A lot of players have this built-in to the UI already. Makes sense that an Android player with a UI would have it as well.

**Comment by zrhoffman** [comment]
Double-tap the left side of the screen to cycle through zoomed and unzoomed:

```conf
0x10001 cycle-values video-zoom 0.5 0.0
```

**Comment by sfan5** [comment]
Possible with custom gestures.
