### ISSUE TITLE
Modifying cache size can't effective

### ISSUE THREAD

**Issue by loroid** [mpv-android/mpv-android#347]
I have set the cache size to 512m, but it's still 32m
![](https://i.imgur.com/GtQ83c2.jpg)
![](https://i.imgur.com/aSCB135.jpg)

**Comment by sfan5** [comment]
I have doubts that your config is being loaded at all since mpv-android (currently) does not come with functioning Vulkan support -> you should not be having video output at all. Maybe it's erroring on the first invalid setting?

Check [`logcat`](https://developer.android.com/studio/command-line/logcat) to see what's wrong.

**Comment by loroid** [comment]
@sfan5 I deleted config about Vulkan and it's working, Thanks.

**Comment by KaKi87** [comment]
Hello, this feature (`demuxer-max-bytes`) was really hard for me to find, would you mind enhancing accessibility, for user experience ? Thanks.
