### ISSUE TITLE
File picker: Add a way to play back network streams

### ISSUE THREAD

**Issue by scottywz** [mpv-android/mpv-android#35]
It would be nice to have an "enter URL" option in the file picker screen.

**Comment by Vintodrimmer** [comment]
I have somewhat similar request.

I mostly use video player for .webm files from imageboards and when I try to watch any of them, `mpv-android ` doesn't show up in the `open with` dialogue screen, unlike other video players.

I'm guessing that it has to do with its inability to handle external links, because I can play them if I previously download the files.
