### ISSUE TITLE
Target mpv not found

### ISSUE THREAD

**Issue by qyihu** [mpv-android/mpv-android#352]
Hello there,

print **_Target mpv not found** error while I executed the **./buildall.sh** command.

Please help me to take a look if I missed something?

**Comment by purvagevaria** [comment]
@qyihu I was facing the same issue in past. 
- Command sequences should be 
 ./include/download-sdk.sh
./include/download-deps.sh
./buildall.sh --arch arm64 mpv
./buildall.sh --arch x86_64 mpv
./buildall.sh

 I missed arch arm65 mpv sequence that's why I was facing the issue. I am not sure it will work in your case or not but give it a try.
