### ISSUE TITLE
[Question] How can I call the app from a website?

### ISSUE THREAD

**Issue by Maverick-2000** [mpv-android/mpv-android#366]
Can someone please help me.
I want to call the app from my website like  href: `intent:${url}#Intent;package=is.xyz.mpv 
can someone help me with the correct syntax

**Comment by sfan5** [comment]
Documentation is here: https://developer.chrome.com/docs/multidevice/android/intents/

If I understand that correctly you'd use `intent://mpv.io/images/mpv-logo-128-0baae5aa.png#Intent;package=is.xyz.mpv;scheme=https;end;` to play `https://mpv.io/images/mpv-logo-128-0baae5aa.png`. Haven't tested however.

**Comment by Maverick-2000** [comment]
> Documentation is here: https://developer.chrome.com/docs/multidevice/android/intents/
> 
> If I understand that correctly you'd use `intent://mpv.io/images/mpv-logo-128-0baae5aa.png#Intent;package=is.xyz.mpv;scheme=https;end;` to play `https://mpv.io/images/mpv-logo-128-0baae5aa.png`. Haven't tested however.

I tried this but for some reason it gets redirected to playstore

**Comment by sfan5** [comment]
Okay figured it out: <b>`intent://mpv.io/images/mpv-logo-128-0baae5aa.png#Intent;type=video/any;package=is.xyz.mpv;scheme=https;end;`</b>

Since our manifest filters depending on MIME type or URLs with a few select extensions (mkv, mp4, webm, m3u, ...) you need to trick Android into opening mpv anyway by specifying a valid-looking type.

**Comment by mk202020212022** [comment]
First time you click the intent starts playing. Pressing back button and click again opens paused.
