### ISSUE TITLE
Add support for Vapoursynth

### ISSUE THREAD

**Issue by csolisr** [mpv-android/mpv-android#38]
Vapoursynth is a library that allows MPV to control the playback of media using Python scripts. In particular, it is possible to use both in tandem for motion interpolation, upscaling content to display smoothly at 60 FPS even if the original video is not: https://kaangenc.me/mpv/

To enable Vapoursynth, MPV must be compiled with the library enabled, and said library must be bundled with the application.

**Comment by sfan5** [comment]
Are you sure any **Android** device is good enough to handle motion interpolation or any of the fancy upscalers one can use with vapoursynth?

**Comment by brucethemoose** [comment]
Vapoursynth is rather CPU heavy. You'd be better off with the mpv user shaders for scaling on Android. 

https://github.com/mpv-player/mpv/wiki/User-Scripts

I'd actually be interested to see if the 820 or 835 GPUs are fast enough for AdaptiveSharpen, as it looks fantastic on the desktop. 

Mpc-qt has a nice UI for the shaders:

https://github.com/cmdrkotori/mpc-qt?files=1

But I'm not sure how easy it would be to port over.

**Comment by shack-32** [comment]
We should be able to use the open-gl interpolation filter right, since we are already using scale and dscale. I'll maybe try to add and test it but I'm by no means a developer, so it might fail..

https://mpv.io/manual/master/#options-interpolation

**Comment by JimmyHoffa** [comment]
I should think my nvidia shield TV is capable. Perhaps other Android TV devices as well; which really are the ones that would benefit from this feature.

**Comment by xyzz** [comment]
Actually it's probably not. You can see here: https://www.phoronix.com/scan.php?page=article&item=nvidia-tegra-x1&num=1 they benchmarked it and compared to an i3 5010U, it is still behind the i3.

Now let's assume tegra x1 equals i3 5010u. looking at a different benchmark we can see it gets about 3k points at https://www.cpubenchmark.net/cpu.php?cpu=Intel+Core+i3-5010U+%40+2.10GHz

In the post linked, Intel i7 4700MQ is specified, https://www.cpubenchmark.net/cpu.php?cpu=intel+core+i7-4700mq+%40+2.40ghz which gets over 2x score

so yes, any android device is likely too slow for any sort of reasonable cpu motion interpolation

As a side note, interpolation option in mpv is different because it's not motion-based, but rather convolution-based, so the result looks completely different. https://github.com/mpv-player/mpv/wiki/Interpolation

I'm not sure if we should keep this issue open, is there any non cpu-heavy workload for vapoursynth?

**Comment by shack-32** [comment]
One thing I noticed when using FFMpeg to interpolate was that I could not force it on more than 1 core, and it was very slow, don't know if we will run into the same error here on MPV.

One of the most lightweight implementations of video interpolation I've seen is http://www.dmitrirender.ru/, however that is a directshow filter.. But I don't think we can easily port that...

**Comment by brucethemoose** [comment]
"is there any non cpu-heavy workload for vapoursynth?"

There are some OpenCL denoising filters, but they're waaaaaay too heavy for real-time playback, much less playback on an Android GPU. 

As far as motion interpolation goes, there's also bluesky/AMD fluid motion, but that's also directshow. 


I think we should close this issue. HOWEVER, I think MPV's GPU-based user shaders should be a serious consideration (maybe open a new issue for it), as Android GPU power is increasing at a pretty staggering rate. Many are already faster than Intel IGPs.

**Comment by jewelsonn** [comment]
> Are you sure any **Android** device is good enough to handle motion interpolation or any of the fancy upscalers one can use with vapoursynth?

SVP Player is the proof.

**Comment by xyzz** [comment]
as far as I know, SVP does something completely different here, hence the requirement for OpenCL on Android builds
