### ISSUE TITLE
Problem decoding H264 10-bit video on a Tablet

### ISSUE THREAD

**Issue by rolandojp** [mpv-android/mpv-android#423]
Hi,

When playing H264 10-bit videos, mpv is unable to decode it with either hardware or software decoding: video is totally black and sometimes the upper part shows some kind of artifacts but I can still listen to the audio and the subtitles are shown properly.

The hardware that I'm using is a Samsung Galaxy Tab A 8.4 tablet that has a Exynos 7904 processor with ARM Mali-G71 MP2 graphics.

I've tried playing the same files with VLC and MX Player and they play without issues.

If you need more info, please ask and I'm more than willing to provide to help solve this issue.

Thanks in advance.

![Screenshot_20210629-061610_mpv](https://user-images.githubusercontent.com/86665811/123804290-f19f1100-d8a1-11eb-821e-e1a25228b497.png)

**Comment by sfan5** [comment]
You're likely seeing two different problems that look identical:
* With hardware decoding, 10-bit will fail to decode but not fall back to software decoding. This is known and we don't have a workaround.
* 10-bit video will sometimes not render at all (all black) on certain GPUs. You can put `vf=format=yuv420p` in your config to work around this.

**Comment by T-10001** [comment]
Are there any downsides to using `vf=format=yuv420p`?

**Comment by sfan5** [comment]
Technically yes, in practice not really.
It will convert down to 8-bit, negating advantages of 10-bit (but if 10-bit doesn't work what's the alternative?). More importantly it also converts other formats that'd otherwise work fine (YUV 4:4:4, RGB) to `yuv420p` losing a bit of color information and wasting some CPU time. In practice almost everything you watch is `yuv420p/yuv420p10` so this is not particularly relevant.
