### ISSUE TITLE
what's the mpv.config for playing 4K HDR?

### ISSUE THREAD

**Issue by vrindavan** [mpv-android/mpv-android#433]
It currently set to none because I don't know what to put there so the 4K HDR has bad color and video plays as if it's corrupted or something which it isn't. All other settings are untouched. It's on factory default.

**Comment by sfan5** [comment]
mpv should play HDR reasonably well on default settings, specifically for Android you probably have to disable hwdec since that's 8-bit only.
Another issue might be that [`--hdr-compute-peak`](https://mpv.io/manual/master/#options-hdr-compute-peak) usually does not work on phones/tables/TV boxes due to (GPU) hardware limitations.

**Comment by vrindavan** [comment]
Yes, the movie is 10bit. But SW just lags. That's why I use HW.

**Comment by vrindavan** [comment]
Hey @sfan5 I do not remember but I had some config earlier which used to play HDR very well. Now it is lost and it is just making stuff really dull. Can you give me the config so that I can just paste it there?

**Comment by sfan5** [comment]
I couldn't possibly know which configuration you used before. If you say "dull" then it might be that you adjusted the tonemapping algorithm.

**Comment by vrindavan** [comment]
I found the config on some website that removed it now. No luck. I did not change any setting but it just plays very colorless now. I will just close this issue. Let me know if you can help.
