### ISSUE TITLE
Android TV mpv as external player for Kodi

### ISSUE THREAD

**Issue by sillus81** [mpv-android/mpv-android#443]
I see, mpv is not in android tv/google tv play-store but in google playstore (mobile). But I could sideload it on my chromecast (2021) and player is opening its own as app. I installed it to use as external player (more [https://kodi.wiki/view/HOW-TO:Use_external_players_on_Android]here(url) for kodi to try it instead of default DS player. But it doesn't lauch the player when clicking 'Play' in kodi. I heard other players like MX player or VLC are playing fine. It says " "External player active, Click "OK" when playback has ended". It doesn't show payer window. As in the guide I replaced the android app activity with 'is.xyz.mpv' for mpv player. Any way to launch the player in Kodi?

**Comment by sfan5** [comment]
How it launches external players depend on how you configure Kodi, this is better suited for their issue tracker.

**Comment by HengyueLi** [comment]
+1 
I meet the same problem. I guess it should be discussed there. In the Kodi config file, the setting `is.xyz.mpv` is filled in the filename. It should be a bin file to run mpv. So the problem is: where is the bin file of MPV in Android.  I guess the path of the bin file `is.xyz.mpv` is incorrect.
