### ISSUE TITLE
Is there a way to use MPV Plugins on Android? If so, how?

### ISSUE THREAD

**Issue by MintMain21** [mpv-android/mpv-android#456]
What drove me to trying MPV on (Linux) Desktop was the spnsorblock_minimalist plugin, alongside a few others.

What drove me to trying MPV Android was both a want to easily enqueue media shared through chats and internet browsing and my own dang curiosity regarding MPV Plugins.

I can only presume either there's a file location to drop plugins like on Desktop, or not. If there is one, I'm having difficulty finding it.

I don't NEED MPV Plugin support in theory (Firefox on Android supports SponsorBlock again for example) but if it is possible I would jump at the chance to try all my favorite Desktop plugins on Android.

### Additional information

Using the latest MPV Android build (the fork with YT-DLP support), on Android 10 I believe, with a mostly default configuration (disabled some touch gestures, enabled Background Play, and set a preferred quality for YT Playback, and that's it).

**Comment by sfan5** [comment]
The answer is yes. You can extract scripts at any app-readable location(\*) and put use the [`script`](https://mpv.io/manual/master/#options-script) option in mpv.conf to point mpv towards it.
If you have a rooted device you can also directly write to `/data/user/0/is.xyz.mpv/files/scripts`.
(\* This will stop working eventually because Android 10 wants to prevent apps from just reading the entire internal storage.)

[sponsorblock_minimal](https://codeberg.org/jouni/mpv_sponsorblock_minimal) is a different matter:
From a quick look it wants either Lua-cURL or `curl` as a command line utility, neither of which will be present.
It won't work in its current form, but would be <i>possible</i> to rewrite the script to call out to python (shipped with mpv-android) for its HTTP request. It could then work on Android.

**Comment by piyushgarg** [comment]
hello @sfan5, I wanted you to think about some plugin framework to extend the mpv-android functionality just like kodi has it. For eg: yt-dlp port. The purpose is to let the open source community build features around mpv-android. The plugins could be download from the mpv-android repo and can be installed/uninstalled.
