### ISSUE TITLE
[Pixel 6] 10-bit files play incorrectly using hardware decoding

### ISSUE THREAD

**Issue by jarnedemeulemeester** [mpv-android/mpv-android#462]
### Important information

Android version: 12.0

mpv-android version: 2021-10-28-release / 26 (release)
mpv version: 0.33.0-397-g4a80de90d2
I'm also using mpvlib (v0.34) in a personal project which has the same problem. This is build using [this project](https://github.com/CarlosOlivo/mpv-android/tree/libmpv).

Which version of mpv-android introduced the problem (if known): Unkown

### Description

I am unable to correctly play any 10-bit files with mpv-android (or the library included in my own project) using hardware decoding. Software decoding works fine.
This problem occurs using hevc and h.264. I have not tested other codecs. 
This is the result of a [hevc file](https://jell.yfish.us/media/jellyfish-3-mbps-hd-hevc-10bit.mkv):

![Screenshot_20211128-142725](https://user-images.githubusercontent.com/32322857/143769857-44efef78-3e44-499a-a82b-b1e8afd64416.png)

10-bit hevc files are always distorted green while 10-bit h.264 files are usually just black.

### Log output

[jellyfish-3-mbps-hd-hevc-10bit.mkv.log](https://github.com/mpv-android/mpv-android/files/7613618/jellyfish-3-mbps-hd-hevc-10bit.mkv.log)

### Additional information

ExoPlayer is able to play the hevc files just fine.
VLC also plays the hevc fine (using hardware decoding I think).
10-bit h.264 however doesn't work on both ExoPlayer and VLC.
My Pixel 3 is able to play these files fine with mpv-player using hardware decoding.

The Pixel 6 has a SoC called Google Tensor which is using a combination of Google and Samsung components. The hardware decoder seems to be an Exynos part.

While looking at the logs I noticed it is using yuv420p as pixel format. Shouldn't this be yuv420p10le? I'm no expert, it's just something I noticed.

I don't really care about 10-bit h.264 since this has always been problematic. 10-bit hevc is what is really important since a lot of content is in this format nowadays.

**Comment by sfan5** [comment]
> While looking at the logs I noticed it is using yuv420p as pixel format. Shouldn't this be yuv420p10le? I'm no expert, it's just something I noticed.

Indeed. 10-bit content doesn't fit into yuv420p unless of course it was converted down to 8-bit first.
It's unclear how 10-bit is supposed to work *at all* because MediaCodec's API does not provide any 10-bit formats.
See also: https://github.com/mpv-android/mpv-android/issues/371#issuecomment-783455654, [`MediaCodecInfo.CodecCapabilities`](https://developer.android.com/reference/android/media/MediaCodecInfo.CodecCapabilities?hl=en#constants_1)
https://github.com/mpv-player/mpv/pull/9324 would probably work fine because that leaves the RGB conversion up to MediaCodec. (maybe give the APK there a try)

Making 10-bit work with `mediacodec-copy` (at least on your device) should also be possible but will require in-depth debugging to figure out 1) what the actual pixel format of the buffers is and 2) how this can be detected.

**Comment by Pentaphon** [comment]
> I am unable to correctly play any 10-bit files with mpv-android (or the library included in my own project) using hardware decoding. Software decoding works fine.

This happens to me as well on a Snapdragon 460 device and I suspect it has to do with buggy video decoders on the stock firmware, but only so far on the Jellyfish file. It works fine on other 10-bit x265 files.

**Comment by Nalsai** [comment]
I'm having the same issue and can confirm that the patched APK works. Funnily, the Google Photos app has this issue too in the thumbnails, but it works when playing.

**Comment by jarnedemeulemeester** [comment]
I tested the same file again and now it works flawlessly using hardware decoding :smile: 

I don't know what fixed the issue but these things have changed since I had the issue:
Android version: 13 Build T1B2.220916.004 (QPR1 beta 2)
mpv-android version: 2022-07-30-release / 29 (release)
mpv version: 0.34.0-386-g284fecc0bd

I'm closing this now since it's fixed on my device.
