### ISSUE TITLE
Fails to play any video

### ISSUE THREAD

**Issue by kerpi4** [mpv-android/mpv-android#479]
### Important information

Android version: 6.0

mpv-android version: 2021-10-28-release / 26 (release)

Which version of mpv-android introduced the problem (if known): 2021-10-28-release / 26 (release)

### Description

When I try to play a video, local or URL, immediately closes it and slides back to the file browser.

### Log output

https://0x0.st/oswb.log

**Comment by sfan5** [comment]
mpv recently had a bug where context creation would fail if GL ES 3.0 was not available, I suspect this is it. This was fixed in November but the fix obviously is not in the release build.
Please try this APK I produced the other day: https://kitsunemimi.pw/tmp/mpv-android-2021-12-15.apk

**Comment by kerpi4** [comment]
It shows a blue screen with working audio and only SW decoder aviable. Here is the log again if it helps: https://0x0.st/osYw.log

**Comment by sfan5** [comment]
No hwdec is expected since that APK also includes a brand new implementation that doesn't work on older Android. Broken video output is not expected and I just pushed a fix for that (https://github.com/mpv-player/mpv/commit/57bc5ba6d6579d5f1e6897f6915a3a940b84bb73).
Here's one where everything should work fine: https://kitsunemimi.pw/tmp/mpv-android-2022-01-02.apk

**Comment by kerpi4** [comment]
Yes, it works.

PS: I'm probably missing something, but it says hwdec now:
![Screenshot_2022-01-02-17-01-47](https://user-images.githubusercontent.com/10427847/147880160-ded9aa6a-97d5-460b-b22b-ae369276e780.png)
