### ISSUE TITLE
mpv-android is outdated on F-Droid, is there a specific repository to add for a newer mpv-android releases ?

### ISSUE THREAD

**Issue by sebma** [mpv-android/mpv-android#505]
Hi, mpv-android is outdated on F-Droid (2021-10-28-release), is there a specific repository (like [IzzyOnDroid](https://apt.izzysoft.de/fdroid/) or something else) to add for newer mpv-android releases ?

**Comment by Eskuero** [comment]
Randomly came across this issue. If you are willing to try it I maintain a repo which contains mpv builds too.

https://repo.fromshado.ws/

Note that all apps there are built directly from their respective master branch instead of tagged releases so they might break without warning and only the last built is kept.

**Comment by Chr0matic1** [comment]
They take a few more days to be made available on F-Droid. The last three versions were there 9, 14 and 3 days after release

**Comment by sfan5** [comment]
F-Droid always builds apps entirely from source and is maintained by volunteers. As already mentioned judging by previous releases it'll be on there in a few days or a week.

**Comment by linsui** [comment]
I have updated mpv for F-Droid [yesterday](https://gitlab.com/fdroid/fdroiddata/-/commit/18afdc2e6e53ee2fd5a69901225034a6b0e1154d) but a bug in fdroidserver blocked it. The bug has been fixed and mpv should be built this time.
