### ISSUE TITLE
Content suddenly starts to stutter

### ISSUE THREAD

**Issue by ghost** [mpv-android/mpv-android#519]
### Important information

Android version: 12

mpv-android version: 0.34.0 (22.02.06 F-droid)

Which version of mpv-android introduced the problem (if known): It was present in previous versions too.

### Description

Describe your issue in detail here.

Sometimes (probably when doing heavy tasks like opening files or quick scrolling and switching audio or video channels) the stream (both video and audio) suddenly starts to stutter. I have not observed IF this only happens at H264 .mkv or other formats as well. Restarting, wiping cache, force stop does not work. This has happened multiple times before. I have not observed when or how this goes away but suddenly it does. Really annoying. Samsung One UI 4.0

### Log output

–

### Additional information

Video: https://0x0.st/obDb.mp4

![image14](https://user-images.githubusercontent.com/94188674/162609903-5f80b079-a824-4a45-bcd5-848c5597fc43.png)

**Comment by Etim-Orb** [comment]
Still present as of 03.23 build. This probably mainly happens with the sample media I have provided.

**Comment by gardenappl** [comment]
> If I turn off the audio, the video doesn't stutter.

Happens to me as well, it keeps running out of cached data and then stuttering, but with audio disabled I consistently 1.0 seconds of "Total Cache" without stuttering.

Happens with videos downloaded via NewPipe and sped up more than 1x.

**Comment by divVerent** [comment]
I have recently encountered this same issue with files that are "badly interleaved".

You can use GPAC to create such a file out of any MP4 (should be a few hundred MiB) like this:

```
MP4Box -add input.mp4 -flat -new output.mp4
```

EDIT: with files written by _this_ the issue does not happen. Is there an explicit detection for bad interleaving that detects this but not the files that app produces?

I don't know why yet, but the issue is a lot more pronounced in

https://f-droid.org/repo/is.xyz.mpv_41.apk (2025-04-21-release)

than in

https://f-droid.org/repo/is.xyz.mpv_42.apk (2025-07-27-release)

So has something been done about it recently?

**Comment by sfan5** [comment]
You will have to check the mpv and ffmpeg changelogs.
