### ISSUE TITLE
Auto load next file

### ISSUE THREAD

**Issue by C1fer** [mpv-android/mpv-android#535]
Once you open a file, the player should append all files that follow the current one to a playlist. I know you can already load a playlist by long-pressing a folder, but the generated playlist isn't very useful if you have subdirectories.

I'm basically asking for the same functionality as the autoload script. I've tried loading it by modyfing mpv.conf, but it doesn't seem to work.

**Comment by C1fer** [comment]
Already tried that, but it doesn't seem to work.

**Comment by BhaturaGuy** [comment]
I am pretty sure it works and _without_ root.
![Screenshot_2022-06-06-22-42-34-60_fb5bde98493fac6ba1b634d4cd01a49f](https://user-images.githubusercontent.com/93109835/172211266-daac14e8-be3f-40bf-b2b0-b421d63dc740.jpg)
It even adds next and previous file button

**Comment by qgustavor** [comment]
If you are not using the api29 build then scripts will probably not work since mpv cannot access non-media files. [As said in the changelog](https://github.com/mpv-android/mpv-android/releases/tag/mpv-android-2022-03-23) a fix is being worked on. I imagine this fix will add an "Open scripts folder" button in the settings which automatically add the path to the folder to mpv.conf using the Scoped Storage *thing*.

**Comment by C1fer** [comment]
Api29 build works great with autoload. Thanks for the help.

**Comment by sfan5** [comment]
> [As said in the changelog](https://github.com/mpv-android/mpv-android/releases/tag/mpv-android-2022-03-23) a fix is being worked on. I imagine this fix will add an "Open scripts folder" button in the settings which automatically add the path to the folder to mpv.conf using the Scoped Storage _thing_.

FYI the "fix being worked on" only applies to loading media files. Loading scripts is very likely to remain broken. What mpv-androd would need is a full blown script manager.
