### ISSUE TITLE
QUESTION: Should the file picker depend on android's media scanner?

### ISSUE THREAD

**Issue by xaeiougit** [mpv-android/mpv-android#539]
Hi,

Long term mpv user here, but new to mpv-android.  It's working great on my phone, but on my NVIDIA Shield:

Android Version:11
Shield Version: 9.0.2(33.1.0.319)
mpv-android version: 0.34.0-235 (built March 23 - playstore version)

The file picker does not show media files, only directories.  After spending some time looking for permissions and other issues, I remembered I have "Scan for media automatically" disabled on my Shield.  I turned it back on, and files appeared in the mpv-android's file picker.

This isn't a show stopper for me because I can use another file picker app and "open with" mpv-android.  However I'm curious on opinions about the pros and cons of this dependency.  VLC for example optionally does it's own scan and doesn't seem to depend on the android media scanner.   

After several problems with memory and storage hogging on limited resource devices like the Nvidia Shield (typically because they may connect to huge media libraries), I prefer to turn media scanner off on those type of devices.

**Comment by sfan5** [comment]
Android 11 has introduced some restrictions for apps that want to read the entire shared storage (Google considers this deprecated), now only media files are visible to apps that do this. It seems possible to me that disabling media scanning could break this "feature", though that'd be a bug in Android.

If you download the 'api29' variant from [the releases](https://github.com/mpv-android/mpv-android/releases) then the file picker will probably work as expected but Google Play enforces the restriction I mentioned.

The reason VLC can do this is because they have been granted an [exemption from this restriction](https://developer.android.com/training/data-storage/manage-all-files#all-files-access-google-play) which Google says they will grant apps whose core functionality is e.g. file management (unclear whether media players are meant to fall under this).

mpv-android will get the ability to open a directory path using one of the APIs Google _doesn't_ consider deprecated soon, this will get rid of a bunch of old bugs related to external storage and also allow you to see all files on every device/version again.

**Comment by xaeiougit** [comment]
Thanks very much for the thorough explanation, that makes perfect sense.

I will try the 'api29' variant and see what happens.

In the meantime, it was nice to test and see that alternate file pickers (ES File explorer in my case) work well to select and pass media files to mpv-android.  So this is a good workaround for anyone that hits this same issue, or even a first choice if you want fancy file filtering that goes beyond what could reasonably be expected of mpv-android.  It's good to have options :)
