### ISSUE TITLE
Hardware decoder resizes vertically to full screen and Software decoder doesn't admit custom resizers and filters

### ISSUE THREAD

**Issue by wyup** [mpv-android/mpv-android#541]
Device: Sony X85J
Android version: 10, Mediatek MT5895, Mali-G71
mpv-android version: [2022-03-23] Google Play Armv7, 

### Description
When doing custom mpv.conf and choosing HW decoding as follows:

vo=mediacodec_embed
hwdec=mediacodec

HW decoding is available, however, all videos are resized to fullscreen 16:9 losing original ratio
Also, some videos of older codecs like mpeg4/divx/mpeg2 play in high speed.

When choosing custom SW decoding as follows:

vo=gpu
gpu-context=android

and choosing either of these:
profile=gpu-hq  / scale=ewa_lanczossharp  / deband=yes

video playback is blank while audio and searchbar is available

### Log output
Don't know how to adb to my tv wirelessly at the moment

### Expected behaviour:
Correct resizing and framerate playback in hardware decoding. In software decoding, availability to select custom resizers and filters.

**Comment by sfan5** [comment]
> HW decoding is available, however, all videos are resized to fullscreen 16:9 losing original ratio

mediacodec_embed is a very barebones VO. From the top off my head I don't know whether the issues you described are solvable, but I doubt there is developer interest in this from the mpv side.

> When choosing custom SW decoding as follows:

You seem to be equating vo_gpu to software decoding. This is not accurate, hardware decoding is still possible with `hwdec=mediacodec-copy`.

> profile=gpu-hq / scale=ewa_lanczossharp / deband=yes
> video playback is blank while audio and searchbar is available

Lastly this is the same root cause as https://github.com/mpv-android/mpv-android/issues/392#issuecomment-803570934
Vulkan could help make this work even on devices where Open GLES fails but mpv-android currently can't do it. (see #482 for current efforts on Vulkan support)

**Comment by wyup** [comment]
I did not equate vo=GPU to software decoding, I knew hwdec=mediacodec-copy is available, I meant full software decoding for best deciding quality.
It is strange that we ever need Vulkan for simple custom resizer, which is the core of a specialized video player like mpv. What is the default resizer actually? My Sony Tv has 1.28 Vulkan driver, by the way.
And Kodi for Android has support for Spline64 and Lanczos3, so it's definitely doable.

**Comment by sfan5** [comment]
> Which is the default resizer actually?

Bilinear, just using linear texture sampling in OpenGL.

> And Kodi for Android has support for Spline64 and Lanczos3, so it's definitely doable by the GPU.

What I described in the other issue is my current educated guess, there can be other factors. mpv prefers high precision (16-bit) GPU buffers (can make a difference). The Kodi team has much more people who could potentially add workarounds for things that don't work the ordinary way on mobile GPUs. etc.
