### ISSUE TITLE
HDR tablet

### ISSUE THREAD

**Issue by Jamie666123** [mpv-android/mpv-android#570]
Type the contents of your question here.

Hi there I am trying to get hdr videos working on my tablet in full hdr as the screen supports hdr 10 however when I add lines to my config such as - - target prim by.2020 and I change the output and trc to PQ everything gets washed out can someone please help me I’m very new to mpv

**Comment by OrangeColaJuice** [comment]
Try 
target-prim=apple
or
target-prim=dci-p3

these seem to be the most common 95-100% covered wide gamut color spaces on most phones, according to measurements but it also depends on the color setting in the default menu.
Check for my phone: https://www.devicespecifications.com/en/editor-review/4f1676/3
The 3 main settings are very ambigous, first gives you color space - DCI-P3, second gives you Adobe RGB third clamps the phone to sRGB BT709 - yet this behavior is not documented in the menu.

**Comment by sfan5** [comment]
mpv on Android does not support the required APIs for native HDR support.

**Comment by OrangeColaJuice** [comment]
Strange. I think Android's own HDR mode does tone-mapping to device gamut alongside offering the dynamic range thing if available.
But this MPV player gives washed up colors on normal mode if I do target-prim=bt.2020 lke OP did
but gives me vivid and correct colors if It tone-maps to the actual measured phone gamut (wider than the default bt.709 to which it auto tone-maps) It's also possible to simulate HDR behavior with peak brightness, the manual explains it.

What's the catch?

**Comment by sfan5** [comment]
> if it tone-maps to the actual measured phone gamut (wider than the default bt.709 to which it auto tone-maps)

are you sure it does that? did you check with stats.lua?

> What's the catch?

No idea, I can only tell you that native HDR output is not supported.

**Comment by OrangeColaJuice** [comment]
Another example
dither-depth=no (disable any dithering on MPV's side)
load https://www.eizo-apac.com/static/uploads/files/16bitgradation-wfuncyaztzod.tif
I see a pretty smooth transition as expected on a 10 bit display

Another test: https://www.wide-gamut.com/assets/test/image-red-P3.jpg
I pass this one as well.

I also took a sample clip on my bt709 display (which we assume that MPV or android would clamp colors to, right?) and set it to Adobe RGB colorspace and color-calibrated bt709... the Android one looks exactly like the color calibrated bt709 instead of the distorted Adobe RGB.

Stats.lua don't seem to report the color transformation but it does report that the file I'm playing is wide-gamut 10 bit encoded, on my computer MPV auto tone-maps it to bt709

**Comment by sfan5** [comment]
> Is there any work planned for that?

Currently not, I don't even know if the technical requirements are provided by Android these days.

**Comment by mirh** [comment]
Even android 14 in 2023 [wouldn't](https://developer.qualcomm.com/blog/adding-hdr-video-capabilities-android-apps) support [native](https://developer.android.com/media/grow/hdr-playback) hdr? Uh?
