### ISSUE TITLE
New version no longer offered as choice in Jellyfin

### ISSUE THREAD

**Issue by panama007** [mpv-android/mpv-android#574]
### Important information

Android version: Fire OS 6.2.9.0 (NS6290/4022)

mpv-android version:
`mpv-android-2022-07-30`; I tried both `app-default-armeabi-v7a-release.apk` and `app-api29-universal-release.apk`

Which version of mpv-android introduced the problem (if known):
The versions listed above

### Description

With the previously installed `mpv-android-api29-2022-03-23.apk`, whenever I'd open a video file in Jellyfin, Android would ask me whether I wanted to open it in `mpv` or `vlc` (I have that installed as well). After updating to the new version I no longer get that choice; it opens only in `vlc`, as if Android didn't think the new version was a video player. After reverting to the previous version everything works again.

**Comment by sfan5** [comment]
Barring some policy change that depends on app updates (what?) the only change that could have caused this is https://github.com/mpv-android/mpv-android/commit/7a277d8100256f55d05735890af7b8ec6cc8c53c.
That change was made since in #514 someone reported that removing the host qualifier could help with a bug on Android 12.
