### ISSUE TITLE
Support --config-dir, profiles and/or launch parameters

### ISSUE THREAD

**Issue by ghost** [mpv-android/mpv-android#616]
I don't understand why isn't this supported.

On windows I could make mpv portable and point to the config directory with --config-dir and it loads up stuffs from that directory.

But on mpv-android, this became a hassle. I would have to keep a directory of mpv config somewhere in the storage, then whenever I edit the mpv.conf on the storage I would have to paste it into the mpv-android's mpv.conf.

Not only this is annoying, but because it also doesn't load fonts. Yes, I would like to install a font to use it. But it only loads from the config-dir's font directory, which mpv-android fails to because it doesn't support --config-dir.

And if I don't keep the two identical versions of mpv.conf between the storage and the mpv-android itself, uninstalling mpv-android would mean deleting the mpv.conf and input.conf within.

This isn't consistent with the fact that lua scripting is loaded externally. If that's the case, then mpv-android should also support --config-dir.

On Windows I could have separate bat with different config-dir or settings, which allows separate usage with one mpv.exe. On Android this isn't possible, with addition with all that hassles above.

Please add --config-dir and the ability to have profiles/choosing different --config-dir or something. Or support the usage of launch parameters instead that allows configuring the settings with most flexibility.

Thank you.

**Comment by sfan5** [comment]
This might have been a good idea a few years ago, but the scoped storage changes in Android 10/11 make this nonviable.
Namely Android only allows whitelisted access to `/sdcard` based on the file extension, so mpv probably can't even see any `.conf` or `.ttf` files created there.

**Comment by Quackdoc** [comment]
it does work on android 10 with api29 builds, add include=/sdcard/something/mpv.conf. 

its worth noting that https://github.com/mpv-player/mpv/pull/9856 also works with this too. I wonder if we can set these as compile time options

**Comment by rihaq** [comment]
> I don't understand why isn't this supported.
> 
> On windows I could make mpv portable and point to the config directory with --config-dir and it loads up stuffs from that directory.
> 
> But on mpv-android, this became a hassle. I would have to keep a directory of mpv config somewhere in the storage, then whenever I edit the mpv.conf on the storage I would have to paste it into the mpv-android's mpv.conf.
> 
> Not only this is annoying, but because it also doesn't load fonts. Yes, I would like to install a font to use it. But it only loads from the config-dir's font directory, which mpv-android fails to because it doesn't support --config-dir.
> 
> And if I don't keep the two identical versions of mpv.conf between the storage and the mpv-android itself, uninstalling mpv-android would mean deleting the mpv.conf and input.conf within.
> 
> This isn't consistent with the fact that lua scripting is loaded externally. If that's the case, then mpv-android should also support --config-dir.
> 
> On Windows I could have separate bat with different config-dir or settings, which allows separate usage with one mpv.exe. On Android this isn't possible, with addition with all that hassles above.
> 
> Please add --config-dir and the ability to have profiles/choosing different --config-dir or something. Or support the usage of launch parameters instead that allows configuring the settings with most flexibility.
> 
> Thank you.

The dev is very bad. Although android is locked/limited like ios the dev won't let us enjoy all fuctions of mpv. Even Outplayer (mpv in ios) supports most of desktop mlv features with extra stuffs like google drive support. He won't let us 😔  integrate mpv with termux using a termux plugin app (like termux-tasker, termux:api) if he had did this we could use any mpv scripts and install dependencies like python, node.js, aria2c etc. from termux, even yt-dlp( no need to build separate mpv apk) Launch mpv with extra flags from termux.He will keep the UI ugly forever, We know keybinds/ keyboard shortcut in android due to limitations of keyboard and extra keys but he can atleast add those options in those options in OSC like a button to take screenshot etc. The dev also has a habit to to hide build scripts, he hates open-source. iirc mpv with youtube-dl apk build script is not published in github

**Comment by Quackdoc** [comment]
Don't slander. 
your only evidence of this is wrong, both the yt-dl branch and the python branch are open source. 
if you want google drive, use rcx and android's document UI. 
add the integration yourself if you want it.

**Comment by qgustavor** [comment]
Is it possible to use some the Scoped Storage Access API to allow the user to select a folder in storage then pass the virtual folder path this API provides to mpv?
Also, VLC for Android from Google Play supports access to all files, not just media files. If VLC manages that, what stops mpv-android from doing the same as both are video/audio players?

**Comment by sfan5** [comment]
> Is it possible to use some the Scoped Storage Access API to allow the user to select a folder in storage then pass the virtual folder path this API provides to mpv?

Nope, not possible. Making this work would require lots of integration work inside mpv because standard C functions (`fopen`, ...) do not work to interact with Scoped Storage.

> Also, VLC for Android from Google Play supports access to all files, not just media files. If VLC manages that, what stops mpv-android from doing the same as both are video/audio players?

vlc has the `MANAGE_EXTERNAL_STORAGE` permission which requires an approval process from google before you can publish your app.
