### ISSUE TITLE
Android navigation bar overlaps the player

### ISSUE THREAD

**Issue by da3dsoul1** [mpv-android/mpv-android#677]
I'm using android 13 and the latest mpv build, default setting, when I click on the playing video navigation bar pops up, is there anyway to fix that? I don't want it to open by default, only when swiping from the bottom of screen.
![Untitled](https://user-images.githubusercontent.com/111184581/224625805-26aee4c0-be44-461f-90a6-fda0a5262b06.png)

**Comment by da3dsoul1** [comment]
Found the fix via the magisk module that disables navigation bar altogether https://github.com/Magisk-Modules-Alt-Repo/HideNavBar , though it's not ideal for everybody for me it's a perfect solution. Also i've read that there's a setting for an app developer to disable the bar in their apps, dunno how it can be implemented though, hope the solution I posted can help some people in need.

**Comment by moneytoo** [comment]
On Android tablets (12L+), the bottom taskbar fully overlaps player controls:

![Screenshot_20230323_081124](https://user-images.githubusercontent.com/1071643/227129870-faa5a7d6-451d-4e99-a315-19c42c246f81.png)

[device-2023-03-23-080515.webm](https://user-images.githubusercontent.com/1071643/227128598-336462b6-629e-4136-85dd-8bcbd78bd556.webm)

**Comment by sfan5** [comment]
Apparently this needs to be handled via insets: https://developer.android.com/about/versions/12/12L/summary#dev-handle-insets

**Comment by sfan5** [comment]
It just occurred to me that _disabling_ "Extend video into the notch/cutout area" in settings should fix this, anyone can verify?

**Comment by moneytoo** [comment]
> It just occurred to me that _disabling_ "Extend video into the notch/cutout area" in settings should fix this, anyone can verify?

I tried disabling that option on both a phone and a tablet but it didn't help.

**Comment by sam-gq** [comment]
After the latest update, the cutout was appeared when the video is in fullscreen mode, and the setting **_Extend video into the notch/cutout area_** was disappeared.
![Screenshot_20230605-205839_1](https://github.com/mpv-android/mpv-android/assets/80607823/4bcc3c7e-d72d-416e-aa6c-10392fe9c466)
_This is a test image in immersive mode (panscan)_

I still like this feature, but I'd like to revert this update to watch immersive videos/anime all the time.

But the gesture navigation still persist the issue, there is the only solution. Try to untick _**Show controls at the bottom of screen**_ to fix a problem.
![Screenshot_20230605-205739~01](https://github.com/mpv-android/mpv-android/assets/80607823/c32ff997-a925-4b00-8cb3-801d682597b8)

![Screenshot_20230605-205254_1 1](https://github.com/mpv-android/mpv-android/assets/80607823/4104a60c-bc2c-4d94-9edb-6ae1d3ca080a)
Otherwise, the player UI needs to be ajusted regardless of the display size or window size on the big screen.

**Comment by sam-gq** [comment]
> I'm having trouble identifying which problem you are describing. Are you saying that the video should extend into the empty space on the right side?

Yes, there is a notch/punch hole on the right side that I'm saying. It should extend the cutout area to fill the video all the way.

**Comment by sfan5** [comment]
I see.
Could you create a [new issue](https://github.com/mpv-android/mpv-android/issues/new?assignees=&labels=&projects=&template=1_bug_report.md&title=) of this with a short description so I can track this properly?

**Comment by sam-gq** [comment]
> I see. Could you create a [new issue](https://github.com/mpv-android/mpv-android/issues/new?assignees=&labels=&projects=&template=1_bug_report.md&title=) of this with a short description so I can track this properly?

Yes, as I can do in the morning.
