### ISSUE TITLE
Is it possible to use HW decoding for audio ?

### ISSUE THREAD

**Issue by Nojevah** [mpv-android/mpv-android#870]
Some audio players can use "system" decoders instead of their own (I guess ffmpeg) library.
If I use "adb top" in shell, during audio playback (using phone loudspeaker, to avoid Bluetooth conversion), with a USB cable, I can monitor differences between players.

mpv, like every video players, does NOT use system decoders for audio. Even Samsung video player won't use hardware decoder for audio, so I guess it's not possible when there's a video, but who knows, maybe it's possible and nobody has attempted that ? I wanted to know if nobody is interested in this feature for video player, since the idea is to gain on video HW decoding only ?
Or if it's just not possible for example to keep video and audio in sync ?
Or it's just that you use ffmpeg for lots of things so let's use it for audio decoding too ?

I though using hardware decoding would prevent any audio treatment, but Vanilla music player manages to handle ReplayGain for example (only player to me who can achieve HW + replayGain).

### Additional information

Phone info: Samsung A52s with Snapdragon 778G, Android 13 (One UI 5.1)
A flac audio file launched with Vanilla music player (could have used Tiny Music Player too), then click on home button, then turn screen off, wait some seconds with "top -m 22 -d 5":

![image](https://github.com/mpv-android/mpv-android/assets/7541249/55271456-2dc3-4663-91ae-07b9a1943805)

The same file, same condition, played with mpv:

![image](https://github.com/mpv-android/mpv-android/assets/7541249/14785053-a920-4822-91c6-77854345d572)

**Comment by sfan5** [comment]
In short: on the typical device a video player runs on the computing resources needed for audio decoding is vastly smaller than what you need to invest for video decoding & presentation (the primary target of optimization), so nobody bothers with audio hardware decoding. Desktop platforms typically don't even _have_ any hardware for this.
Exceptions to this are:
- Audio Passthrough, which was done not to save computing resources but rather because external audio devices (e.g. home theater system) are expected to do special things when operating on the encoded audio stream, rather than already decoded PCM data.
- Android apps who do not want to bring their own decoders. These have to rely on the system codecs and get hwdec for free if it exists.

You can try [passthrough](https://mpv.io/manual/master/#options-audio-spdif) if it works for you (only select codecs), but other than that nobody will invest effort into this because it's not worth it.
