### ISSUE TITLE
Enabling GPU debanding in settings flips output vertically

### ISSUE THREAD

**Issue by xyzz** [mpv-android/mpv-android#89]
Most of the time it looks flipped, but about 1-3 per second for a frame it "jumps around" back to normal

mpv: d588bdaaf7473685ce85438c0a7b80c77f719ece
mpv-android: 572fa2dca984fb9c00cd7b47816f650b964937dd

**Comment by sfan5** [comment]
sounds like GPU driver bug, enabling any of the glsl shader stuff does many weird things on different devices
not much we can do

**Comment by xyzz** [comment]
it used to work fine on this device

**Comment by xyzz** [comment]
further testing indicates that this only happens when I have both GPU debanding and video sync set to display-resample

**Comment by sfan5** [comment]
could reproduce on my tablet and can confirm that `video-sync=display-resample` is required.
also happens with `scale=spline36` instead of deband
<pre>
01-08 17:09:34.203 18835 18901 V mpv     : [vo/gpu/opengl:v] GL_VENDOR='Qualcomm'
01-08 17:09:34.203 18835 18901 V mpv     : [vo/gpu/opengl:v] GL_RENDERER='Adreno (TM) 330'
</pre>
