### ISSUE TITLE
Opening scripts etc. without external storage permission

### ISSUE THREAD

**Issue by jmir1** [mpv-android/mpv-android#924]
Maybe this is kind of out of scope for this repo, but I'll ask here anyways.

Is it feasible to add a handler for content:// URIs to mpv so we can open scripts and subtitles on newer android versions without the need for special permissions?

I'm kind of interested in implementing this but I wanted to ask for some pointers before trying this.

I recently saw that ffmpeg added support for android content uris (https://github.com/FFmpeg/FFmpeg/blob/master/libavformat/file.c#L532-L684) so i thought it could be possible to do the same thing in mpv.

The way I would go about it is creating a new file (like [stream/stream_file.c](https://github.com/mpv-player/mpv/blob/master/stream/stream_file.c)) that implements the opening/closing, etc. functions for android content URIs specifically.

I'd be thankful for some feedback on whether you think this is feasible and if I have got the right approach in mind.

**Comment by sfan5** [comment]
You don't even need to copy the same code into mpv. If ffmpeg has a protocol, mpv can easily make use of it.

Then if you convince the scripting code to load from this protocol (and not just the filesystem) you might get the loading to work.
This falls apart as soon as a lua script tries to load anything with `dofile`, because then you have Lua trying to `fopen` a content:// URL.

You can read my thoughts about how scripts could be "properly" supported here: https://github.com/mpv-android/mpv-android/issues/709#issuecomment-1542775752

> so we can open [...] subtitles on newer android versions without the need for special permissions?

You don't need special permissions for that. Picking external subtitles and audio is possible with a document picker.
